/* Auto-generated by tools/build_manifest.py — do not edit */
#ifndef POKECRYSTAL_ASSETS_MANIFEST_H
#define POKECRYSTAL_ASSETS_MANIFEST_H

#include <stddef.h>
#include <stdint.h>

#ifndef GB_ASSET_ENTRY_DEFINED
#define GB_ASSET_ENTRY_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint32_t size;
    const char* path;
} GBAssetEntry;
#endif

#define POKECRYSTAL_ASSETS_MANIFEST_COUNT 170

static const GBAssetEntry POKECRYSTAL_ASSETS_MANIFEST[POKECRYSTAL_ASSETS_MANIFEST_COUNT] = {
    { 0x00000000, 0x00000004, "code/rst0.bin" }, /* rst0 bank 00 */
    { 0x00000008, 0x00000003, "code/rst8.bin" }, /* rst8 bank 00 */
    { 0x00000010, 0x00000006, "code/rst10.bin" }, /* rst10 bank 00 */
    { 0x00000018, 0x00000001, "code/rst18.bin" }, /* rst18 bank 00 */
    { 0x00000020, 0x00000001, "code/rst20.bin" }, /* rst20 bank 00 */
    { 0x00000028, 0x0000000b, "code/rst28.bin" }, /* rst28 bank 00 */
    { 0x00000038, 0x00000001, "code/rst38.bin" }, /* rst38 bank 00 */
    { 0x00000040, 0x00000003, "code/vblank.bin" }, /* vblank bank 00 */
    { 0x00000048, 0x00000003, "code/lcd.bin" }, /* lcd bank 00 */
    { 0x00000050, 0x00000003, "code/timer.bin" }, /* timer bank 00 */
    { 0x00000058, 0x00000003, "code/serial.bin" }, /* serial bank 00 */
    { 0x00000060, 0x00000003, "code/joypad.bin" }, /* joypad bank 00 */
    { 0x00000100, 0x00000050, "code/header.bin" }, /* Header bank 00 */
    { 0x00000150, 0x00003e65, "code/home.bin" }, /* Home bank 00 */
    { 0x00004000, 0x0000347b, "code/bank1.bin" }, /* bank1 bank 01 */
    { 0x00008000, 0x00003829, "code/bank2.bin" }, /* bank2 bank 02 */
    { 0x0000c000, 0x00003a0b, "code/bank3.bin" }, /* bank3 bank 03 */
    { 0x00010000, 0x00003d96, "code/bank4.bin" }, /* bank4 bank 04 */
    { 0x00014000, 0x000034ba, "code/bank5.bin" }, /* bank5 bank 05 */
    { 0x00018000, 0x00003dfe, "data/tileset_data_1.bin" }, /* Tileset Data 1 bank 06 */
    { 0x0001c000, 0x0000030c, "data/roofs.bin" }, /* Roofs bank 07 */
    { 0x0001c30c, 0x00003010, "data/tileset_data_2.bin" }, /* Tileset Data 2 bank 07 */
    { 0x0001f31c, 0x00000c50, "data/extra_songs_1.bin" }, /* Extra Songs 1 bank 07 */
    { 0x00020000, 0x00000181, "data/clock_reset.bin" }, /* Clock Reset bank 08 */
    { 0x00020181, 0x00003990, "data/tileset_data_3.bin" }, /* Tileset Data 3 bank 08 */
    { 0x00023b11, 0x00000440, "data/egg_moves.bin" }, /* Egg Moves bank 08 */
    { 0x00024000, 0x00003a2d, "code/bank9.bin" }, /* bank9 bank 09 */
    { 0x00028000, 0x00003a1a, "code/banka.bin" }, /* bankA bank 0a */
    { 0x0002ba1a, 0x000002d0, "gfx/trainer_backpics.bin" }, /* Trainer Backpics bank 0a */
    { 0x0002c000, 0x00002f9f, "code/bankb.bin" }, /* bankB bank 0b */
    { 0x00030000, 0x000033f0, "data/tileset_data_4.bin" }, /* Tileset Data 4 bank 0c */
    { 0x00034000, 0x00003ee2, "data/effect_commands.bin" }, /* Effect Commands bank 0d */
    { 0x00038000, 0x00003a67, "data/enemy_trainers.bin" }, /* Enemy Trainers bank 0e */
    { 0x0003c000, 0x00003e86, "battle/battle_core.bin" }, /* Battle Core bank 0f */
    { 0x00040000, 0x000025b1, "code/bank10.bin" }, /* bank10 bank 10 */
    { 0x000425b1, 0x000016ab, "data/evolutions_and_attacks.bin" }, /* Evolutions and Attacks bank 10 */
    { 0x00044000, 0x00000997, "code/bank11.bin" }, /* bank11 bank 11 */
    { 0x00048000, 0x00002e78, "data/crystal_features_1.bin" }, /* Crystal Features 1 bank 12 */
    { 0x0004c000, 0x00001249, "code/bank13.bin" }, /* bank13 bank 13 */
    { 0x0004d249, 0x000000d0, "gfx/shrink_pics.bin" }, /* Shrink Pics bank 13 */
    { 0x0004d319, 0x00002003, "data/bank13_2.bin" }, /* bank13_2 bank 13 */
    { 0x00050000, 0x00003d9c, "code/bank14.bin" }, /* bank14 bank 14 */
    { 0x00053d9c, 0x00000092, "data/unused_egg_pic.bin" }, /* Unused Egg Pic bank 14 */
    { 0x00054000, 0x00003322, "data/map_scripts_1.bin" }, /* Map Scripts 1 bank 15 */
    { 0x00058000, 0x00003712, "data/map_scripts_2.bin" }, /* Map Scripts 2 bank 16 */
    { 0x0005c000, 0x00003099, "data/map_scripts_3.bin" }, /* Map Scripts 3 bank 17 */
    { 0x00060000, 0x0000328e, "data/map_scripts_4.bin" }, /* Map Scripts 4 bank 18 */
    { 0x00064000, 0x00003308, "text/crystal_phone_text.bin" }, /* Crystal Phone Text bank 19 */
    { 0x00068000, 0x00003a67, "data/map_scripts_5.bin" }, /* Map Scripts 5 bank 1a */
    { 0x0006c000, 0x000036a4, "data/map_scripts_6.bin" }, /* Map Scripts 6 bank 1b */
    { 0x00070000, 0x000036ed, "data/map_scripts_7.bin" }, /* Map Scripts 7 bank 1c */
    { 0x00074000, 0x00003282, "data/map_scripts_8.bin" }, /* Map Scripts 8 bank 1d */
    { 0x00078000, 0x000036a8, "data/map_scripts_9.bin" }, /* Map Scripts 9 bank 1e */
    { 0x0007c000, 0x00003628, "data/map_scripts_10.bin" }, /* Map Scripts 10 bank 1f */
    { 0x00080000, 0x000023c8, "code/bank20.bin" }, /* bank20 bank 20 */
    { 0x00084000, 0x000028f7, "code/bank21.bin" }, /* bank21 bank 21 */
    { 0x00088000, 0x00003a24, "data/crystal_features_2.bin" }, /* Crystal Features 2 bank 22 */
    { 0x0008c000, 0x00003f0d, "code/bank23.bin" }, /* bank23 bank 23 */
    { 0x00090000, 0x00003a3d, "code/bank24.bin" }, /* bank24 bank 24 */
    { 0x00094000, 0x000026b0, "data/maps.bin" }, /* Maps bank 25 */
    { 0x000966b0, 0x000018ce, "data/events.bin" }, /* Events bank 25 */
    { 0x00098000, 0x00003bf8, "data/map_scripts_11.bin" }, /* Map Scripts 11 bank 26 */
    { 0x0009c000, 0x00003bb2, "data/map_scripts_12.bin" }, /* Map Scripts 12 bank 27 */
    { 0x000a0000, 0x00001eca, "data/phone_scripts_1.bin" }, /* Phone Scripts 1 bank 28 */
    { 0x000a4000, 0x000024ad, "text/phone_text.bin" }, /* Phone Text bank 29 */
    { 0x000a8000, 0x00003fab, "data/map_blocks_1.bin" }, /* Map Blocks 1 bank 2a */
    { 0x000ac000, 0x00003f5a, "data/map_blocks_2.bin" }, /* Map Blocks 2 bank 2b */
    { 0x000b0000, 0x00001b42, "data/map_blocks_3.bin" }, /* Map Blocks 3 bank 2c */
    { 0x000b4000, 0x00003ea8, "data/tileset_data_5.bin" }, /* Tileset Data 5 bank 2d */
    { 0x000b8000, 0x00001e8b, "code/bank2e.bin" }, /* bank2E bank 2e */
    { 0x000bc000, 0x00002699, "data/phone_scripts_2.bin" }, /* Phone Scripts 2 bank 2f */
    { 0x000c0000, 0x00003fc0, "gfx/sprites_1.bin" }, /* Sprites 1 bank 30 */
    { 0x000c4000, 0x00003f80, "gfx/sprites_2.bin" }, /* Sprites 2 bank 31 */
    { 0x000c8000, 0x00003d2e, "code/bank32.bin" }, /* bank32 bank 32 */
    { 0x000cbd2e, 0x00000100, "data/the_end.bin" }, /* The End bank 32 */
    { 0x000cc000, 0x00003d9e, "data/move_animations.bin" }, /* Move Animations bank 33 */
    { 0x000cfd9e, 0x00000166, "data/extra_songs_2.bin" }, /* Extra Songs 2 bank 33 */
    { 0x000d0000, 0x00003c33, "data/pic_animations_1.bin" }, /* Pic Animations 1 bank 34 */
    { 0x000d4000, 0x00002240, "data/pic_animations_2.bin" }, /* Pic Animations 2 bank 35 */
    { 0x000d8000, 0x00000400, "data/font_inversed.bin" }, /* Font Inversed bank 36 */
    { 0x000d8400, 0x00001866, "data/pic_animations_3.bin" }, /* Pic Animations 3 bank 36 */
    { 0x000dc000, 0x00003d90, "data/tileset_data_6.bin" }, /* Tileset Data 6 bank 37 */
    { 0x000e0000, 0x000037f9, "code/bank38.bin" }, /* bank38 bank 38 */
    { 0x000e4000, 0x000001d0, "data/copyright.bin" }, /* Copyright bank 39 */
    { 0x000e41d0, 0x0000389d, "code/bank39.bin" }, /* bank39 bank 39 */
    { 0x000e8000, 0x000014e9, "data/audio.bin" }, /* Audio bank 3a */
    { 0x000e94e9, 0x00002ada, "data/songs_1.bin" }, /* Songs 1 bank 3a */
    { 0x000ec000, 0x00003ef5, "data/songs_2.bin" }, /* Songs 2 bank 3b */
    { 0x000f0000, 0x00000941, "data/songs_3.bin" }, /* Songs 3 bank 3c */
    { 0x000f0941, 0x00001e46, "audio/sound_effects.bin" }, /* Sound Effects bank 3c */
    { 0x000f2787, 0x0000182f, "data/cries.bin" }, /* Cries bank 3c */
    { 0x000f4000, 0x00003ef3, "data/songs_4.bin" }, /* Songs 4 bank 3d */
    { 0x000f8000, 0x00003e91, "code/bank3e.bin" }, /* bank3E bank 3e */
    { 0x000fc000, 0x000011d2, "code/bank3f.bin" }, /* bank3F bank 3f */
    { 0x00100000, 0x0000389d, "data/mobile40.bin" }, /* mobile40 bank 40 */
    { 0x00104000, 0x00002dbd, "code/bank41.bin" }, /* bank41 bank 41 */
    { 0x00108000, 0x00001407, "data/mobile42.bin" }, /* mobile42 bank 42 */
    { 0x00109407, 0x00000440, "gfx/intro_logo.bin" }, /* Intro Logo bank 42 */
    { 0x00109847, 0x00001e09, "data/credits.bin" }, /* Credits bank 42 */
    { 0x0010c000, 0x00003f5e, "gfx/title.bin" }, /* Title bank 43 */
    { 0x00110000, 0x00003f84, "data/mobile_adapter_sdk.bin" }, /* Mobile Adapter SDK bank 44 */
    { 0x00114000, 0x00001d99, "data/mobile_adapter_sdk_mail.bin" }, /* Mobile Adapter SDK Mail bank 45 */
    { 0x00115d99, 0x00001f49, "data/mobile45.bin" }, /* mobile45 bank 45 */
    { 0x00118000, 0x00003c9e, "data/mobile46.bin" }, /* mobile46 bank 46 */
    { 0x0011c000, 0x00003686, "battle/battle_tower.bin" }, /* Battle Tower bank 47 */
    { 0x00120000, 0x000005ee, "data/pic_pointers.bin" }, /* Pic Pointers bank 48 */
    { 0x001205ee, 0x00003a0c, "gfx/pics_1.bin" }, /* Pics 1 bank 48 */
    { 0x00124000, 0x0000009c, "data/unown_pic_pointers.bin" }, /* Unown Pic Pointers bank 49 */
    { 0x0012409c, 0x00003f62, "gfx/pics_2.bin" }, /* Pics 2 bank 49 */
    { 0x00128000, 0x000000c9, "data/trainer_pic_pointers.bin" }, /* Trainer Pic Pointers bank 4a */
    { 0x001280c9, 0x00003f35, "gfx/pics_3.bin" }, /* Pics 3 bank 4a */
    { 0x0012c000, 0x00004000, "gfx/pics_4.bin" }, /* Pics 4 bank 4b */
    { 0x00130000, 0x00003fff, "gfx/pics_5.bin" }, /* Pics 5 bank 4c */
    { 0x00134000, 0x00003fff, "gfx/pics_6.bin" }, /* Pics 6 bank 4d */
    { 0x00138000, 0x00004000, "gfx/pics_7.bin" }, /* Pics 7 bank 4e */
    { 0x0013c000, 0x00003ff7, "gfx/pics_8.bin" }, /* Pics 8 bank 4f */
    { 0x00140000, 0x00004000, "gfx/pics_9.bin" }, /* Pics 9 bank 50 */
    { 0x00144000, 0x00004000, "gfx/pics_10.bin" }, /* Pics 10 bank 51 */
    { 0x00148000, 0x00003ffb, "gfx/pics_11.bin" }, /* Pics 11 bank 52 */
    { 0x0014c000, 0x00004000, "gfx/pics_12.bin" }, /* Pics 12 bank 53 */
    { 0x00150000, 0x00003fe3, "gfx/pics_13.bin" }, /* Pics 13 bank 54 */
    { 0x00154000, 0x00004000, "gfx/pics_14.bin" }, /* Pics 14 bank 55 */
    { 0x00158000, 0x00003ffa, "gfx/pics_15.bin" }, /* Pics 15 bank 56 */
    { 0x0015c000, 0x00003fff, "gfx/pics_16.bin" }, /* Pics 16 bank 57 */
    { 0x00160000, 0x00003ffc, "gfx/pics_17.bin" }, /* Pics 17 bank 58 */
    { 0x00164000, 0x000029d3, "gfx/pics_18.bin" }, /* Pics 18 bank 59 */
    { 0x00168000, 0x000029d3, "gfx/pics_19.bin" }, /* Pics 19 bank 5a */
    { 0x0016c000, 0x000017fe, "code/bank5b.bin" }, /* bank5B bank 5b */
    { 0x00170000, 0x0000368c, "data/mobile5c.bin" }, /* mobile5C bank 5c */
    { 0x00174000, 0x00003561, "text/crystal_phone_text_2.bin" }, /* Crystal Phone Text 2 bank 5d */
    { 0x00178000, 0x0000001f, "battle/updatebattlehuds.bin" }, /* UpdateBattleHUDs bank 5e */
    { 0x0017801f, 0x0000180e, "data/songs_5.bin" }, /* Songs 5 bank 5e */
    { 0x0017982d, 0x000001c2, "audio/crystal_sound_effects.bin" }, /* Crystal Sound Effects bank 5e */
    { 0x001799ef, 0x00001c4a, "data/mobile5e.bin" }, /* mobile5E bank 5e */
    { 0x0017c000, 0x00003f6c, "data/mobile5f.bin" }, /* mobile5F bank 5f */
    { 0x00180000, 0x00001695, "data/map_scripts_13.bin" }, /* Map Scripts 13 bank 60 */
    { 0x00181695, 0x00001b0d, "text/pokedex_entries_001_064.bin" }, /* Pokedex Entries 001-064 bank 60 */
    { 0x00184000, 0x0000247f, "data/map_scripts_14.bin" }, /* Map Scripts 14 bank 61 */
    { 0x00188000, 0x00003778, "data/map_scripts_15.bin" }, /* Map Scripts 15 bank 62 */
    { 0x0018c000, 0x00003441, "data/map_scripts_16.bin" }, /* Map Scripts 16 bank 63 */
    { 0x00190000, 0x00003688, "data/map_scripts_17.bin" }, /* Map Scripts 17 bank 64 */
    { 0x00194000, 0x000036c0, "data/map_scripts_18.bin" }, /* Map Scripts 18 bank 65 */
    { 0x00198000, 0x00003ac7, "data/map_scripts_19.bin" }, /* Map Scripts 19 bank 66 */
    { 0x0019c000, 0x00003643, "data/map_scripts_20.bin" }, /* Map Scripts 20 bank 67 */
    { 0x001a0000, 0x000030b1, "data/map_scripts_21.bin" }, /* Map Scripts 21 bank 68 */
    { 0x001a4000, 0x00003337, "data/map_scripts_22.bin" }, /* Map Scripts 22 bank 69 */
    { 0x001a8000, 0x0000388a, "data/map_scripts_23.bin" }, /* Map Scripts 23 bank 6a */
    { 0x001ac000, 0x00002796, "data/map_scripts_24.bin" }, /* Map Scripts 24 bank 6b */
    { 0x001b0000, 0x00002042, "text/phone_text_2.bin" }, /* Phone Text 2 bank 6c */
    { 0x001b2042, 0x00000071, "data/map_scripts_25.bin" }, /* Map Scripts 25 bank 6c */
    { 0x001b4000, 0x00003633, "text/special_phone_text.bin" }, /* Special Phone Text bank 6d */
    { 0x001b8000, 0x00001adb, "text/pokedex_entries_065_128.bin" }, /* Pokedex Entries 065-128 bank 6e */
    { 0x001bc000, 0x0000208d, "text/text_1.bin" }, /* Text 1 bank 6f */
    { 0x001c0000, 0x00001ec9, "text/text_2.bin" }, /* Text 2 bank 70 */
    { 0x001c4000, 0x0000211e, "text/text_3.bin" }, /* Text 3 bank 71 */
    { 0x001c8000, 0x00002ecd, "text/miscellaneous_text.bin" }, /* Miscellaneous Text bank 72 */
    { 0x001cc000, 0x00001b51, "text/pokedex_entries_129_192.bin" }, /* Pokedex Entries 129-192 bank 73 */
    { 0x001d0000, 0x00001931, "text/pokedex_entries_193_251.bin" }, /* Pokedex Entries 193-251 bank 74 */
    { 0x001dc000, 0x000001b0, "data/unown_font.bin" }, /* Unown Font bank 77 */
    { 0x001dc1b0, 0x000003f1, "data/print_party.bin" }, /* Print Party bank 77 */
    { 0x001dc5a1, 0x00001108, "data/tileset_data_7.bin" }, /* Tileset Data 7 bank 77 */
    { 0x001dd6a9, 0x00000c3b, "code/bank77.bin" }, /* bank77 bank 77 */
    { 0x001de2e4, 0x000002e4, "data/pok_gear_gfx.bin" }, /* Pokégear GFX bank 77 */
    { 0x001de5c8, 0x00000c70, "data/european_mail.bin" }, /* European Mail bank 77 */
    { 0x001e0000, 0x00001000, "data/tileset_data_8.bin" }, /* Tileset Data 8 bank 78 */
    { 0x001ec000, 0x00000f02, "battle/battle_tower_text.bin" }, /* Battle Tower Text bank 7b */
    { 0x001f0000, 0x000009d8, "battle/battle_tower_trainer_data.bin" }, /* Battle Tower Trainer Data bank 7c */
    { 0x001f4000, 0x0000236a, "data/mobile_news_data.bin" }, /* Mobile News Data bank 7d */
    { 0x001f8000, 0x000038a8, "data/crystal_events.bin" }, /* Crystal Events bank 7e */
    { 0x001ffde0, 0x00000220, "data/stadium_2_checksums.bin" }, /* Stadium 2 Checksums bank 7f */
};

#endif
