/* Generated by gbrecomp */
#ifndef pokecrystal_H
#define pokecrystal_H

#include "gbrt.h"

const GBConfig* pokecrystal_default_config(void);
void pokecrystal_run(GBContext* ctx);
void pokecrystal_init(GBContext* ctx);
int pokecrystal_main(int argc, char* argv[]);

#endif
